parser <- essentials::ArgumentParser()
parser$add.argument("-a", "-b", "-c")
parser$add.argument("-W", "-Wall", "--Wall")
parser$add.argument("-getwd", action = "exit", exit = getwd())
parser$parse.args()
# (essentials::Rscript(file = this.path::this.path(), args = "-h", intern = FALSE))
# (essentials::Rscript(file = this.path::this.path(), args = "-h", intern = TRUE ))
# (essentials::Rscript(file = this.path::this.path(), args = "-getwd", intern = FALSE))
# (essentials::Rscript(file = this.path::this.path(), args = "-getwd", intern = TRUE ))
